### ISSUE TITLE
Backend folder name is not appropriate

### ISSUE THREAD

**Issue by deep-1704** [deep-1704/Job-Posting-Web-App#6]
The name of the folder that contains backend stuff does not look suitable for the project. The name will be too long if we change it to 'JobPostingWebAppBackend' which does not even look formal. 

I would suggest changing the name from 'JobPostingWebApp' to just 'app_backend'. Here, Camel-case is not used because I would be using create-react-app to build the frontend which does not allow Camel-casing the folder name hence I have to name the frontend folder as 'app_frontend'.

**Comment by kravi770** [comment]
Issue Resolved
